export const ERROR_MESSAGE = {
  INVALID_CREDENTIAL: 'USERNAME_OR_PASSWORD_INCORRECT',
  INVALID_OTP: 'TOKEN_INCORRECT',
};

export const JWT_CONFIG = {
  EXPIRE: {
    ADMIN_ACCESS: 3600 * 8,
    ADMIN_REFRESH: 3600 * 24 * 7,
  },
};
