services:
  db:
    container_name: onecoffee-db
    image: postgres:16
    env_file:
      - ./.env
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
      PGDATA: /var/lib/postgresql/data/pgdata
    ports:
      - '${DB_PORT}:5432'
    volumes:
      - ./pgdata:/var/lib/postgresql/data/pgdata
