export const OTP_TTL = 60 * 3;
export const ADMIN_ACCESS_TOKEN_EXPIRED_IN = 1 * 60 * 60;
export const ADMIN_REFRESH_TOKEN_EXPIRED_IN = 3 * 24 * 60 * 60;

export const ERROR_MESSAGE = {
  INVALID_CREDENTIAL: 'USERNAME_OR_PASSWORD_INCORRECT',
  INVALID_OTP: 'TOKEN_INCORRECT',
};
